-- AlterTable
ALTER TABLE `tipo_documento` MODIFY `descricao` ENUM('ATA_ASSINADA', 'CERTIDAO_NASCIMENTO', 'NOTA_FISCAL', 'ORCAMENTO', 'RECIBO', 'NIS', 'LAUDO', 'ATESTADO', 'CERTIFICADO', 'MEMORANDO', 'OFICIO', 'TOMBAMENTO', 'TERMO_DOACAO', 'RG', 'CPF', 'DECLARACAO_VACINACAO', 'COMPROVANTE_RESIDENCIA', 'DOCUMENTO_DO_RESPONSAVEL', 'AUTODECLARACAO_RACIAL') NOT NULL;
